////
 troubleshooting.adoc

-------------------------------------------------------------------------------
   Copyright 2016 Kevin Morey <kevin@redhat.com>

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-------------------------------------------------------------------------------
////

= CloudForms_Infoblox Troubleshooting Guide

* <<Authentication>>
* <<Connectivity>>
* <<Logging>>
* <<Open an Issue>>

== Authentication

** Ensure that your credentials are properly set in the statemachine classes. Sometimes the password just needs to be re-entered.
** Ensure that your provided credentials has sufficient privileges to perform CRUD operations.

<<top>>

== Connectivity

** Ensure that you can get to your Infoblox instance from the CloudForms server.

*** Try this command to ensure that you can return a JSON list of Infoblox host records:

 curl -k -v -H "Accept:application/json" -H "Content-Type:application/json" -u adloxmin:infoblox -X GET https://infoblox.example.com/wapi/v1.7/record:host/

<<top>>

== Logging

** Check the /var/www/miq/vmdb/log/automation.log and /var/www/miq/vmdb/log/evm.log for errors.

<<top>>

== Open an Issue
** Still stuck? Open an issue here with a detailed description of your problem: link:https://github.com/ramrexx/CloudForms_Infoblox/issues[Open an issue]

<<top>>
